name: test

on:
  push:
    tags:
      - 0.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Retrieve tag name
        uses: olegtarasov/get-tag@2.1.3
        id: tag_name

      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          check-latest: true
          cache: 'maven'

      - name: Set version
        run: mvn versions:set -DnewVersion=$GIT_TAG_NAME

      - name: Build
        run: mvn -B package --file pom.xml
