name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          check-latest: true
          cache: 'maven'

      - name: License Header Check
        run: mvn license:check

      - name: Build with Debug Logs
        run: mvn -X clean install --file pom.xml

      - name: Ensure Target Directory Exists
        run: mkdir -p target

      - name: List Target Directory (Debug)
        run: ls -l target || echo "No files found in target/"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-build
          path: target/*.jar
